rm -r crab_tW
rm -r crab_DY
rm -r crab_ttWZ
rm -r crab_Signal_HH_M500
rm -r crab_ttWW
rm -r crab_ttZ
rm -r crab_Signal_HH_M1100
rm -r crab_WZZ
rm -r crab_ttWLNu
rm -r crab_WW_2L
rm -r crab_Signal_HH_M260
rm -r crab_tbar_tch
rm -r crab_Signal_HH_M450
rm -r crab_WPHtoBB
rm -r crab_Signal_HH_M750
rm -r crab_ttZtoQQ
rm -r crab_Signal_HH_M800
rm -r crab_ZHtoBBLL
rm -r crab_GluGluHtoWW
rm -r crab_Signal_HH_M600
rm -r crab_Signal_HH_M350
rm -r crab_SingleMuon_B
rm -r crab_SingleMuon_C
rm -r crab_SingleMuon_D
rm -r crab_SingleMuon_E
rm -r crab_SingleMuon_F
rm -r crab_DY4J
rm -r crab_GluGluHtoZZto2L2Q
rm -r crab_Signal_HH_M2400
rm -r crab_VBFHtoWWto2L
rm -r crab_WJets
rm -r crab_Signal_HH_M1250
rm -r crab_Signal_HH_M1000
rm -r crab_ttHtononBB
rm -r crab_VBFHtoZZto2L
rm -r crab_WPHtoZZto2L
rm -r crab_ggZHtoBB
rm -r crab_ZZ_2L
rm -r crab_Signal_HH_M300
rm -r crab_WMHtoBB
rm -r crab_ZZZ
rm -r crab_Signal_HH_M2200
rm -r crab_Signal_HH_M900
rm -r crab_Signal_HH_M2800
rm -r crab_ZHtoZZto2L
rm -r crab_ttZZ
rm -r crab_Signal_HH_M2600
rm -r crab_Signal_HH_M1300
rm -r crab_WW_1L
rm -r crab_tZq
rm -r crab_Signal_HH_M700
rm -r crab_DY2J
rm -r crab_WWW
rm -r crab_SingleEle_E
rm -r crab_SingleEle_D
rm -r crab_Signal_HH_M650
rm -r crab_SingleEle_F
rm -r crab_SingleEle_C
rm -r crab_SingleEle_B
rm -r crab_Signal_HH_M1900
rm -r crab_ggZHtoWW
rm -r crab_GluGluHtoZZto2L2Nu
rm -r crab_Signal_HH_M2500
rm -r crab_Signal_HH_M1700
rm -r crab_WZ_3L
rm -r crab_Signal_HH_M550
rm -r crab_DY3J
rm -r crab_WWZ
rm -r crab_ttWtoQQ
rm -r crab_WZ_2L
rm -r crab_Signal_HH_M1200
rm -r crab_TTTo1L
rm -r crab_Signal_HH_M270
rm -r crab_WZ_1L
rm -r crab_Signal_HH_M400
rm -r crab_QCD
rm -r crab_Signal_HH_M1800
rm -r crab_VBFHtoBB
rm -r crab_TTTo2L2Nu
rm -r crab_Signal_HH_M1600
rm -r crab_DY1J
rm -r crab_Signal_HH_M1500
rm -r crab_t_sch
rm -r crab_Signal_HH_M3000
rm -r crab_Signal_HH_M2000
rm -r crab_Signal_HH_M1400
rm -r crab_ttHtoBB
rm -r crab_t_tch
rm -r crab_WMHtoZZto2L
rm -r crab_Signal_HH_M1750
rm -r crab_tbarW
