crab status -d crab_tW
crab status -d crab_DY
crab status -d crab_ttWZ
crab status -d crab_Signal_HH_M500
crab status -d crab_ttWW
crab status -d crab_ttZ
crab status -d crab_Signal_HH_M1100
crab status -d crab_WZZ
crab status -d crab_ttWLNu
crab status -d crab_WW_2L
crab status -d crab_Signal_HH_M260
crab status -d crab_tbar_tch
crab status -d crab_Signal_HH_M450
crab status -d crab_WPHtoBB
crab status -d crab_Signal_HH_M750
crab status -d crab_ttZtoQQ
crab status -d crab_Signal_HH_M800
crab status -d crab_ZHtoBBLL
crab status -d crab_GluGluHtoWW
crab status -d crab_Signal_HH_M600
crab status -d crab_Signal_HH_M350
crab status -d crab_SingleMuon_B
crab status -d crab_SingleMuon_C
crab status -d crab_SingleMuon_D
crab status -d crab_SingleMuon_E
crab status -d crab_SingleMuon_F
crab status -d crab_DY4J
crab status -d crab_GluGluHtoZZto2L2Q
crab status -d crab_Signal_HH_M2400
crab status -d crab_VBFHtoWWto2L
crab status -d crab_WJets
crab status -d crab_Signal_HH_M1250
crab status -d crab_Signal_HH_M1000
crab status -d crab_ttHtononBB
crab status -d crab_VBFHtoZZto2L
crab status -d crab_WPHtoZZto2L
crab status -d crab_ggZHtoBB
crab status -d crab_ZZ_2L
crab status -d crab_Signal_HH_M300
crab status -d crab_WMHtoBB
crab status -d crab_ZZZ
crab status -d crab_Signal_HH_M2200
crab status -d crab_Signal_HH_M900
crab status -d crab_Signal_HH_M2800
crab status -d crab_ZHtoZZto2L
crab status -d crab_ttZZ
crab status -d crab_Signal_HH_M2600
crab status -d crab_Signal_HH_M1300
crab status -d crab_WW_1L
crab status -d crab_tZq
crab status -d crab_Signal_HH_M700
crab status -d crab_DY2J
crab status -d crab_WWW
crab status -d crab_SingleEle_E
crab status -d crab_SingleEle_D
crab status -d crab_Signal_HH_M650
crab status -d crab_SingleEle_F
crab status -d crab_SingleEle_C
crab status -d crab_SingleEle_B
crab status -d crab_Signal_HH_M1900
crab status -d crab_ggZHtoWW
crab status -d crab_GluGluHtoZZto2L2Nu
crab status -d crab_Signal_HH_M2500
crab status -d crab_Signal_HH_M1700
crab status -d crab_WZ_3L
crab status -d crab_Signal_HH_M550
crab status -d crab_DY3J
crab status -d crab_WWZ
crab status -d crab_ttWtoQQ
crab status -d crab_WZ_2L
crab status -d crab_Signal_HH_M1200
crab status -d crab_TTTo1L
crab status -d crab_Signal_HH_M270
crab status -d crab_WZ_1L
crab status -d crab_Signal_HH_M400
crab status -d crab_QCD
crab status -d crab_Signal_HH_M1800
crab status -d crab_VBFHtoBB
crab status -d crab_TTTo2L2Nu
crab status -d crab_Signal_HH_M1600
crab status -d crab_DY1J
crab status -d crab_Signal_HH_M1500
crab status -d crab_t_sch
crab status -d crab_Signal_HH_M3000
crab status -d crab_Signal_HH_M2000
crab status -d crab_Signal_HH_M1400
crab status -d crab_ttHtoBB
crab status -d crab_t_tch
crab status -d crab_WMHtoZZto2L
crab status -d crab_Signal_HH_M1750
crab status -d crab_tbarW
